const projectTranslations = {
  'The Circle construction toy': ['Gioco di costruzioni The Circle', 'The Circle e un gioco di costruzioni in legno che trasforma la geometria in un linguaggio creativo. Ispirato allo spirito sperimentale del Bauhaus, esplora modularita, volume e composizione attraverso pezzi pensati per costruire architetture, tipografie e sculture astratte.', 'Grazie alle proporzioni e agli angoli di ogni elemento, le combinazioni sono praticamente infinite. E un oggetto senza eta, progettato per imparare giocando e realizzato con legno proveniente da foreste gestite in modo sostenibile.'],
  'Theatre poster': ['Manifesto teatrale', 'Manifesto scelto dall’Universidad Francisco de Vitoria come immagine ufficiale della rappresentazione di Los intereses creados di Jacinto Benavente. Il progetto reinterpreta l’opera attraverso mani e fili, simboli di manipolazione e legami invisibili.', 'La combinazione di disegno gestuale e acquerello si allontana dal manifesto teatrale tradizionale per offrire una lettura piu contemporanea, emotiva e diretta.'],
  'El Rastro corporate identity': ['Identita visiva El Rastro', 'El Rastro e un’identita visiva progettata per una residenza artistica legata alla memoria urbana di Madrid. Il progetto recupera il peso storico del luogo senza nostalgia, trasformandolo in un’immagine grafica attuale, aperta e culturale.', 'Il logotipo nasce da linee rette e proporzioni architettoniche che richiamano l’angolo di un edificio. La tipografia entra nella struttura come finestre e porte, dando vita a un’identita solida e riconoscibile.'],
  'Harvok typeface': ['Carattere Harvok', 'Progetto di due caratteri sans serif originali, sviluppati in collaborazione a partire da un’idea comune: ridurre la lettera alla sua espressione minima senza perderne l’identita. Le forme lavorano con linee rette, diagonali e geometrie essenziali.', 'Piu che caratteri convenzionali, le proposte diventano un esercizio di percezione visiva. Alcune lettere si completano nella mente del lettore, creando un equilibrio tra ordine, assenza, struttura e intuizione.'],
  'HAZ lamp': ['Lampada HAZ', 'HAZ LAMP e una lampada pensata per accompagnare senza attirare l’attenzione. La luce indiretta crea un’atmosfera calda e tranquilla, filtrata da una carta speciale che rende l’illuminazione uniforme e avvolgente.', 'Realizzata in legno, carta e cartone riciclati, combina semplicita formale e funzionalita in un oggetto leggero, smontabile e riutilizzabile.'],
  'Podcast corporate identity': ['Identita visiva Podcast', 'X-RAIL e un’identita creata per un podcast dedicato a leadership, crescita personale e direzione. La marca nasce dall’idea di una voce vicina capace di accompagnare le persone nei momenti di cambiamento.', 'Il logotipo e costruito con linee che diventano percorsi e lettere. L’identita combina trasparenza ed eleganza per esprimere forza, chiarezza, fiducia e movimento costante.'],
  'Eneo corporate identity': ['Identita visiva Eneo', 'Il marchio nasce per offrire alimentazione di alta qualita a conigli e piccoli roditori, ponendo cura e benessere animale al centro del progetto. L’identita comunica vicinanza, fiducia e attenzione al dettaglio.', 'Il logotipo usa una tipografia minuscola, stretta e disegnata a mano. Il ritmo variabile e le forme arrotondate danno vita a un’identita artigianale, moderna ed elegante.'],
  'Local festivities poster': ['Manifesto delle feste locali', 'Manifesto progettato per le feste locali di San Rafael 2024, concepito come una rappresentazione visiva della vita del paese. Il nome della localita diventa il centro della composizione, attorno al quale emergono strade, tradizioni, attivita e persone.', 'Illustrazione lineare e tipografia tridimensionale costruiscono una grafica festosa e dinamica, pensata per raccontare l’identita e l’energia di San Rafael.'],
  'Editorial design and packaging': ['Design editoriale e packaging', 'Progetto di design editoriale per un gioco di carte con un’identita visiva riconoscibile e immediata. Illustrazione, tipografia e composizione grafica creano un universo dinamico e vicino al pubblico.', 'Il sistema si basa su un personaggio illustrato e su riferimenti al fumetto e ai giochi collezionabili. Il risultato e un packaging coerente, personale e divertente.'],
  'Illustration collection': ['Collezione di illustrazioni', 'Progetto di illustrazione per il catalogo di Plantae, azienda specializzata in soluzioni tecnologiche per il monitoraggio e la gestione delle colture. Il lavoro traduce dati e processi complessi in un linguaggio visivo chiaro e accessibile.', 'Le illustrazioni combinano sintesi grafica, forme semplici e una palette ridotta per raccontare sensori, comunicazioni e strumenti di gestione in modo intuitivo.'],
  'CROSS chair': ['Sedia CROSS', 'CROSS e una sedia bassa in legno di pioppo, costruita con giunti maschio-femmina che ne rafforzano il carattere strutturale e la semplicita formale. La geometria a X definisce telaio e schienale.', 'La struttura genera un gioco di luci e ombre che cambia con il punto di vista. Costruzione e forma lavorano insieme per creare un oggetto leggero, elegante e contemporaneo.'],
  'UFV scenography': ['Scenografia UFV', 'La proposta scenografica suggerisce gli spazi senza bisogno di costruirli completamente. Oggetti quotidiani e riconoscibili permettono allo spettatore di identificare ogni ambiente in modo immediato.', 'Porte, finestre e arredi diventano le chiavi visive di una scenografia leggera, flessibile e centrata sulla percezione.'],
  'Experimental housing and playground': ['Abitazione sperimentale e Playground', 'Padiglione temporaneo progettato per rendere visibile cio che normalmente resta nascosto sottoterra: la complessa rete di tunnel e connessioni di un formicaio. Il progetto trasforma questa struttura in un’esperienza spaziale aperta.', 'Tubi trasparenti intrecciati generano un percorso continuo di curve, vuoti e ombre. Il padiglione propone una riflessione su natura, struttura e movimento.'],
  'Chapel design and lighting': ['Progetto illuminotecnico per cappella', 'Intervento per la cappella ETSAM-UPM, concepito come uno spazio di raccoglimento e silenzio nel contesto universitario. La proposta crea un’atmosfera accogliente e protetta per la preghiera e la riflessione.', 'Con un gesto minimo e attraverso la luce indiretta filtrata da listelli di legno, lo spazio assume il carattere di una grotta serena, calda e contemplativa.'],
  'PG corporate identity': ['Identita visiva PG', 'Permanent Growth e un’identita per una comunita orientata alla crescita personale, professionale e creativa. Il progetto interpreta l’evoluzione come un processo costruito attraverso connessione, apprendimento condiviso e sostegno reciproco.', 'Il logotipo parte dalle iniziali PG, trasformate in una farfalla astratta che rappresenta cambiamento, trasformazione ed espansione.'],
  'Boat sculpture': ['Scultura Boat', 'Boat e una scultura che riduce la forma di un catamarano alla sua essenza piu riconoscibile. Evoca viaggio, esplorazione e curiosita, recuperando la capacita infantile di immaginare e giocare.', 'Ispirata al pensiero di Bruno Munari, usa una geometria semplice per suggerire molto piu di cio che mostra. Il piccolo barco di carta collega l’oggetto ai ricordi e all’immaginazione.'],
  'Office project in the Telefonica building': ['Progetto di uffici nell’edificio Telefonica', 'Progetto di spazi di lavoro flessibili ispirato al Metabolismo giapponese e alle utopie di Archigram. L’ufficio e concepito come un organismo formato da capsule indipendenti e riconfigurabili.', 'I moduli leggeri sembrano staccarsi dall’edificio e fluttuare su una piattaforma, lasciando entrare aria, vegetazione e luce.'],
  'MITECO landscaping project': ['Progetto paesaggistico MITECO', 'Marea e una proposta spaziale ispirata all’idea dell’anello verde di Madrid. Una struttura continua attraversa lo spazio e collega attivita diverse, creando un’esperienza aperta, fluida e in movimento.', 'La geometria ondulata e il gioco delle altezze organizzano il luogo attraverso ritmo, continuita e relazione tra persone e ambiente.'],
  'MITECO landscaping project 2': ['Progetto paesaggistico MITECO 2', 'Questa seconda proposta per lo stesso cliente esplora un rapporto diverso tra geometria, natura e percezione. Siepi scolpite e superfici di terra costruiscono un disegno che organizza il vuoto in modo contemplativo e sensoriale.', 'La composizione lavora sul contrasto tra fondo e forma, pieno e vuoto, luce e ombra, dando vita a una presenza ordinata, viva e contemporanea.'],
  'El Bosque cultural centre': ['Centro culturale El Bosque', 'Il progetto riflette su come ridurre l’architettura alla sua essenza, prendendo come riferimento l’architettura ramificata, la capanna primitiva di Vitruvio e le forme organiche della natura.', 'Una rete di passerelle e capsule leggere organizza lo spazio in modo efficiente e organico, creando un equilibrio tra costruzione, paesaggio, abitabilita e biodiversita urbana.'],
  'Music album art direction': ['Direzione artistica per album musicale', 'Direzione artistica per un album musicale, concepita come un universo visivo che unisce copertina, identita grafica e maglietta in una sola narrazione. Paesaggio rurale, texture invecchiate e una palette calda evocano memoria e origine.', 'Il progetto porta il tono dell’album oltre la musica e costruisce un’identita coerente basata su nostalgia, terra e trasformazione personale.'],
  'Temporary exhibition space 2021': ['Spazio espositivo temporaneo 2021', 'Mangle e una proposta di design ispirata alla struttura organica delle mangrovie e alle radici che si intrecciano. Il progetto esplora ripetizione modulare, equilibrio tra ordine e caos apparente e presenza scultorea.', 'La composizione circolare e la sovrapposizione dei piani generano movimento continuo. Ogni elemento dipende dagli altri per costruire un insieme leggero, dinamico e mutevole.'],
  'V.Karting logo and livery design': ['Design del logo e livrea V.Karting', 'Viciosa Racing e un’identita per un marchio legato al mondo del motore. Il progetto comunica velocita, carattere e passione per la competizione, mantenendo un legame reale con la sua comunita.', 'Il linguaggio grafico contemporaneo dialoga con riferimenti all’estetica classica del marchio Spagna, creando un’identita solida, flessibile e riconoscibile.'],
  'Winery branding and labels': ['Branding ed etichette per cantina', 'SOLDRINK e un’identita per una marca di cocktail in bottiglia che interpreta la bevanda come esperienza sociale, spontanea e piena di energia. Il progetto comunica giovinezza, divertimento e autenticita.', 'L’identita visiva combina freschezza e personalita, valorizzando ingredienti di qualita, origine nazionale e un atteggiamento ottimista e avventuroso.'],
  'Temporary retail stand': ['Stand di vendita temporaneo', 'FLYT’S ACAI e un’identita che porta energia e carattere dell’Amazzonia in un’esperienza di consumo contemporanea. Il progetto unisce salute, gusto e movimento per chi vuole prendersi cura di se senza rinunciare al piacere.', 'Materiali caldi e forme essenziali creano un’atmosfera di rifugio e natura. Lo stand diventa una pausa nel ritmo quotidiano e rende il prodotto accessibile in ogni momento.'],
  "Artists' residency at Nave 16": ['Residenza artistica presso Nave 16', 'El Rastro e una proposta per Matadero Madrid che trasforma una nave in una citta interna per artisti. Recupera l’idea di comunita, scambio e creazione condivisa.', 'Laboratori, abitazioni e spazi espositivi si organizzano attraverso una trama aperta. Materiali e luce dialogano con il carattere industriale del luogo.'],
}

const labels = {
  Area: 'Superficie', Superficie: 'Superficie', Date: 'Data', Fecha: 'Data', Status: 'Stato', Estado: 'Stato', Client: 'Cliente', Cliente: 'Cliente', Team: 'Team', Equipo: 'Team', Awards: 'Premi', Premios: 'Premi', 'Launch project': 'Visita il progetto', 'Launch Project': 'Visita il progetto', 'Ver proyecto': 'Visita il progetto',
}

const values = { Completed: 'Realizzato', Project: 'Progetto', 'Built / Prototype': 'Costruito / Prototipo', Realizado: 'Realizzato', Proyecto: 'Progetto', 'Construido / Prototipo': 'Costruito / Prototipo', 'Coming soon.': 'Prossimamente.' }

function translateFacts(facts) {
  return facts.map((fact) => {
    if (Array.isArray(fact)) return [labels[fact[0]] ?? fact[0], values[fact[1]] ?? fact[1], fact[2]]
    return { ...fact, label: labels[fact.label] ?? fact.label, value: values[fact.value] ?? fact.value }
  })
}

export function getItalianProjectContent(copy) {
  const source = copy.en ?? copy.es
  const translation = projectTranslations[source.title]

  if (!translation) return { ...source, details: 'DATI DEL PROGETTO', facts: translateFacts(source.facts) }

  const [title, ...paragraphs] = translation
  return {
    ...source,
    title,
    alt: `Tavola del progetto ${title}`,
    details: 'DATI DEL PROGETTO',
    paragraphs,
    facts: translateFacts(source.facts),
  }
}
